# Generates src/gguf_grids.ts: the codebook grids of the IQ quantisation types, as gguf-py stores them.
# Requires: pip install gguf numpy   Run from the test directory.
from gguf import quants as Q

names = {'iq2xxs': Q.IQ2_XXS, 'iq2xs': Q.IQ2_XS, 'iq2s': Q.IQ2_S, 'iq3xxs': Q.IQ3_XXS, 'iq3s': Q.IQ3_S, 'iq1s': Q.IQ1_S}
assert Q.IQ1_M.grid_hex == Q.IQ1_S.grid_hex, 'IQ1_M is expected to share the IQ1_S grid'

lines = ['// Codebook grids of the IQ quantisation types, packed as ggml stores them (hex bytes, 2 or 4 bits per entry).', '// Generated by test/make_iq_grids.py from gguf-py: do not edit.', '']
for name, cls in names.items():
    lines.append(f'export const {name} = {{entries: {cls.grid_shape[0]}, width: {cls.grid_shape[1]}, map: {list(cls.grid_map)}, hex: \'{cls.grid_hex.decode()}\'}};')

with open('../src/gguf_grids.ts', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('wrote ../src/gguf_grids.ts:', ', '.join(f'{n} {c.grid_shape}' for n, c in names.items()))
